### ISSUE TITLE
[request] Grafana dashboard

### ISSUE THREAD

**Issue by Rohlik** [kumina/libvirt_exporter#11]
Might I ask you to share some working Grafana dashboard for this exporter?

**Comment by BartVerc** [comment]
[Libvirt_dashboard.json](https://github.com/kumina/libvirt_exporter/files/1994985/Libvirt_dashboard.txt)

This is the dashboard that works for us.

**Comment by Rohlik** [comment]
Thank you for sharing.

**Comment by HeshamAboElMagd** [comment]
This dashboard is not reflecting the collected metrics by the exporter 
The exporter use this prefix " libvirt_domain" but the one expected at the dashboard is not .
Any one have some luck with showing the right data at a grafana dashboard ?

**Comment by HeshamAboElMagd** [comment]
Why to have specific data source inside the json file ? and the variables doesn't even in output metrics from the node exporter

**Comment by BartVerc** [comment]
This dashboard uses recording rules which we have implemented in prometheus. Is that what you mean by "not reflecting the collected metrics"? It was posted as an example.

**Comment by HeshamAboElMagd** [comment]
Yes , I already added the prometheus rules into my prometheus config . still the same
